function HF = default_figure(pos_inches)

set(0, 'DefaultFigureColor', 'White', ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', 8, ...
    'DefaultAxesFontName', 'Arial', ...
    'DefaultAxesFontWeight', 'normal', ...
    'DefaultAxesLineWidth', 1, ...
    'DefaultAxesTickDir', 'Out', ...
    'DefaultAxesBox', 'Off', ...
    'DefaultLineColor', 'Black', ...
    'DefaultLineLineWidth', 1, ...
    'DefaultTextFontUnits', 'Points', ...
    'DefaultTextFontSize', 10, ...
    'DefaultTextVerticalAlignment', 'top', ...
    'DefaultTextFontWeight', 'normal', ...
    'DefaultTextUnits', 'normalized',...
    'DefaultTextFontAngle', 'italic', ...
    'DefaultTextFontName', 'Arial', ...
    'DefaultFigureUnits','inches',...
    'DefaultFigurePosition',[0.0    0.000   11    11]*2/3,...
    'DefaultFigurePaperPositionMode','auto');

%     'DefaultFigurePaperSize',[11 11], ...%[8.26772*(4/3) 8.26772],...

HF=figure('Position', pos_inches);
pos = get(HF,'Position');
set(HF,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3)*1.0, pos(4)*1.0])
HF.Renderer = 'Painters';
